export const fontFamilies = [
	{ label: 'Amatic SC', value: "'Amatic SC', cursive" },
	{ label: 'Bebas Neue', value: "'Bebas Neue', cursive" },
	{ label: 'Caveat', value: "'Caveat', cursive" },
	{ label: 'Courgette', value: "'Courgette', cursive" },
	{ label: 'Dancing Script', value: "'Dancing Script', cursive" },
	{ label: 'Indie Flower', value: "'Indie Flower', cursive" },
	{ label: 'Kiwi Maru', value: "'Kiwi Maru', serif" },
	{ label: 'Lato', value: "'Lato', sans-serif" },
	{ label: 'Lexend', value: "'Lexend', sans-serif" },
	{ label: 'Lobster', value: "'Lobster', cursive" },
	{ label: 'Londrina Solid', value: "'Londrina Solid', cursive" },
	{ label: 'Montserrat', value: "'Montserrat', sans-serif" },
	{ label: 'New Tegomin', value: "'New Tegomin', serif" },
	{ label: 'Nunito', value: "'Nunito', sans-serif" },
	{ label: 'Open Sans', value: "'Open Sans', sans-serif" },
	{ label: 'Pacifico', value: "'Pacifico', cursive" },
	{ label: 'Permanent Marker', value: "'Permanent Marker', cursive" },
	{ label: 'Roboto', value: "'Roboto', sans-serif" },
	{ label: 'Shadows Into Light', value: "'Shadows Into Light', cursive" },
	{ label: 'Train One', value: "'Train One', cursive" },
	{ label: 'Yatra One', value: "'Yatra One', cursive" }
];

export const fontSizes = [
	{ label: '10', value: 10 },
	{ label: '12', value: 12 },
	{ label: '14', value: 14 },
	{ label: '16', value: 16 },
	{ label: '18', value: 18 },
	{ label: '20', value: 20 },
	{ label: '24', value: 24 },
	{ label: '28', value: 28 },
	{ label: '32', value: 32 },
	{ label: '36', value: 36 },
	{ label: '40', value: 40 },
	{ label: '42', value: 42 },
	{ label: '50', value: 50 },
	{ label: '60', value: 64 },
	{ label: '72', value: 72 },
	{ label: '82', value: 82 },
	{ label: '90', value: 90 },
	{ label: '96', value: 96 }
];
